### ISSUE TITLE
 Universal time-based productivity marker.

### ISSUE THREAD

**Issue by BrazilianBug** [BrazilianBug/Prod-Zen#1]
- [x] Adapt interface to support only the counter referring to the respective time.

- [x] Change the hour subtitle to work with current time
- [x] Change value of sum of total completed orders.
- [x] Adapt Java Script to record productivity based on current time.
- [x] Introduce navigation bar.

- [x] Build an interface from which the productivity records will be kept.

**Comment by juanudk** [comment]
[Commit solution](https://github.com/BrazilianBug/Prod-Zen/commit/6274fc2f9b2e13080340c8c75a8398bf106b5d47)
